controller_frequency: 10

TrajectoryPlannerROS:
# Robot Configuration Parameters, these are the velocity limit of the robot
  max_vel_x: 0.4 #0.5
  min_vel_x: -0.1 #0.01
  max_vel_y: 0.4 #0.5
  min_vel_y: -0.1 #0.01
  max_vel_theta: 1.57 #1.5
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.6
#These are the acceleration limits of the robot  
  acc_lim_theta: 3.14
  acc_lim_x: 2.0
  acc_lim_y: 2.0
# Goal Tolerance Parameters: The tolerance of robot when it reach the goal position
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.15
# Forward Simulation Parameters
  sim_time: 3.0
  vx_samples: 3
  vy_samples: 3
  vtheta_samples: 20
# Trajectory Scoring Parameters
  meter_scoring: true
  pdist_scale: 0.6
  gdist_scale: 0.8
  occdist_scale: 0.01
  heading_lookahead: 0.325
  dwa: true
# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05
# Differential-drive robot configuration : If the robot is holonomic configuration, set to true other vice set to false. Chefbot is a non holonomic robot.
  holonomic_robot: true

