controller_frequency: 10

TrajectoryPlannerROS:
# Robot Configuration Parameters, these are the velocity limit of the robot
  max_vel_x: 0.1 #0.5
  min_vel_x: -0.1 #0.01
  max_vel_y: 0.1 #0.5
  min_vel_y: -0.1 #0.01
  max_vel_theta: 1.57 #1.5
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.6
#These are the acceleration limits of the robot  
  acc_lim_theta: 1.54
  acc_lim_x: 0.20
  acc_lim_y: 0.20
# Goal Tolerance Parameters: The tolerance of robot when it reach the goal position
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.15
# Forward Simulation Parameters
  sim_time: 0.30
  vx_samples: 3
  vy_samples: 3
  vtheta_samples: 20
# Trajectory Scoring Parameters
  meter_scoring: true
  pdist_scale: 4.1 # The relative importance of sticking to the global path as opposed to getting to the goal. Set this parameter larger than the gdist_scale to favor following the global path more closely.
  gdist_scale: 0.3 # The relative importance of getting to the goal rather than sticking to the global path. Set this parameter larger than the pdist_scale to favor getting to the goal by whatever path necessary.
  occdist_scale: 4.1 # The relative importance of avoiding obstacles.
  heading_lookahead: 4.00325
  dwa: true # Whether or not to use the Dynamic Window Approach when simulating trajectories into the future.
# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05
# Differential-drive robot configuration : If the robot is holonomic configuration, set to true other vice set to false. Chefbot is a non holonomic robot.
  holonomic_robot: true

