TrajectoryPlannerROS:
  acc_lim_x: 2.0
  acc_lim_y: 2.0
  acc_lim_theta: 3.14
  
  max_vel_x: 0.5 #0.25
  min_vel_x: -0.5 #0.01
  max_vel_theta: 1.5 #1.5
  min_vel_theta: -1.5
  min_in_place_vel_theta: 1.5

  sim_time: 7.5
  sim_granularity: 0.1
  angular_sim_granularity: 0.0157

  pdist_scale: 1.2 #0.6
  gdist_scale: 0.6 #0.8
  occdist_scale: 0.02 
  oscillation_reset_dist: 0.03
  escape_reset_dist: 0.3
  escape_reset_theta: 1.57
  escape_vel: -0.25

  vx_samples: 10.0
  vtheta_samples: 10.0

  heading_lookahead: 0.1
  holonomic_robot: true
  dwa: true
  heading_scoring: false
  heading_scoring_timestep: 0.64

  simple_attractor: false

  meter_scoring: true

  y_vels: 0.5,0.5,0.5,0.5
  
     
