map_type: costmap

obstacle_range: 15.0
raytrace_range: 15.0

robot_radius: 0.10
inflation_radius: 0.15 
cost_scaling_factor: 10.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
