global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 0.5
   publish_frequency: 0.5
   width: 25.0
   height: 18.0
   resolution: 0.01 # The resolution in meters of the rolling map. This should match the resolution set in the YAML file for your map
   static_map: true
   rolling_window: false # The global map is generally not updated as the robot moves to we set this parameter to false
