local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 5.0
   publish_frequency: 5.0
   width: 18.0
   height: 25.0
   resolution: 0.01
   static_map: true
   rolling_window: true

#source_frame base_link
