# .yaml config file
#
# The PID gains and controller settings must be saved in a yaml file that gets loaded
# to the param server via the roslaunch file (my_robot_control.launch).

my_robot:
  # Publish all joint states -----------------------------------
  # Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50   

  # Velocity Controllers -----------------------------------------
  leftFrontWheel_effort_controller:
    type: effort_controllers/JointVelocityController
    joint: left_front_wheel_hinge
    pid: {p: 100.0, i: 0.1, d: 10.0}
  leftBackWheel_effort_controller:
    type: effort_controllers/JointVelocityController
    joint: left_back_wheel_hinge
    pid: {p: 100.0, i: 0.1, d: 10.0}
  rightFrontWheel_effort_controller:
    type: effort_controllers/JointVelocityController
    joint: right_front_wheel_hinge
    pid: {p: 100.0, i: 0.1, d: 10.0}
  rightBackWheel_effort_controller:
    type: effort_controllers/JointVelocityController
    joint: right_back_wheel_hinge
    pid: {p: 100.0, i: 0.1, d: 10.0}
  jackal_velocity_controller:
#    type: "diff_drive_controller/DiffDriveController"
    left_wheel: ['left_back_wheel_hinge', 'left_front_wheel_hinge']
    right_wheel: ['right_back_wheel_hinge', 'right_front_wheel_hinge']
    publish_rate: 50
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    cmd_vel_timeout: 0.25
    velocity_rolling_window_size: 2
   
    base_frame_id: robot_footprint 
    odom_frame_id: '/odom'
    allow_multiple_cmd_vel_publishers: true
    estimate_velocity_from_position: false
    enable_odom_tf: false
    
    wheel_separation : 0.20
    wheel_radius : 0.1
    wheel_separation_multiplier: 1.0 
    wheel_radius_multiplier    : 1.0 
    cmd_vel_timeout: 0.25
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1.0  # m/s
        min_velocity           : -0.5 # m/s
        has_acceleration_limits: true
        max_acceleration       : 0.8  # m/s^2
        min_acceleration       : -0.4 # m/s^2
        has_jerk_limits        : true
        max_jerk               : 5.0  # m/s^3
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 1.7  # rad/s
        has_acceleration_limits: true
        max_acceleration       : 1.5  # rad/s^2
        has_jerk_limits        : true
        max_jerk               : 2.5  # rad/s^3

